2025-03-31 22:30:53 Error: <class 'Exception'> 
 Traceback (most recent call last):
  File "/home/admin/PycharmProjects/TickerK8/TickerK8_updater/APP_FILES/PYTHON/_11_main_Scripts.py", line 86, in setup_main_changelog
    raise # If none
    ^^^^^
RuntimeError: No active exception to reraise
 

